DDOS-109: Improved PurchaseError type
dashdevs/PurchaseController pull request #1
Opened 2019-06-18 12:54 UTC by igor-kulik

- `debugDescription` property;
- `localizedDescription` property; 
- convenience init with `SKError.code`;
- `CustomNSError` protocol conformance.

2019-06-20 08:53 UTC, ValeriyJefimov commented on PurchaseController/Classes/PurchaseErrorHandling.swift
> -/// - unknown: client is not allowed to issue the request, etc.
Should we remove these hints?

2019-06-25 09:07 UTC, DDKirillUshkov requested changes

2019-06-25 09:07 UTC, DDKirillUshkov commented on PurchaseController/Classes/PurchaseErrorHandling.swift
>      func asPurchaseError() -> PurchaseError {
Why not using readonly property instead?

2019-06-25 09:07 UTC, DDKirillUshkov commented on PurchaseController/Classes/PurchaseErrorHandling.swift
> +    func asNSError() -> NSError {
Same as above

2019-06-25 12:37 UTC, ValeriyJefimov approved these changes

2019-06-25 13:40 UTC, DDKirillUshkov approved these changes

2019-06-25 13:40 UTC, merged